# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11473e98ed975fbf4e484bf5c15f66923c97ecb4bcc46c36d526b71c03ec0277279760d8acf556327a2fe733121e2362925e8179b021b85fd1b558c6a02e059a

test:
  secret_key_base: 158123423338f8d83e268f7ac180ef1f7023e82839401b2b258f31474af81667c5f078a23030c4e8fccf16fbec63c2080baf911da9663fa6063bd13955760577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
